/* This file is generated by scripts/build-k0rp-icons.mjs. */
const runtimeUrls = Object.freeze({
  "click-audit": new URL("../assets/icons/korp-v2/click-audit.png", import.meta.url).href,
  "fidget": new URL("../assets/icons/korp-v2/fidget.png", import.meta.url).href,
  "corner-watch": new URL("../assets/icons/korp-v2/corner-watch.png", import.meta.url).href,
  "bubble-wrap": new URL("../assets/icons/korp-v2/bubble-wrap.png", import.meta.url).href,
  "audit-generic": new URL("../assets/icons/korp-v2/audit-generic.png", import.meta.url).href,
  "audit-packet": new URL("../assets/icons/korp-v2/audit-packet.png", import.meta.url).href,
  "evidence": new URL("../assets/icons/korp-v2/evidence.png", import.meta.url).href,
  "inbox": new URL("../assets/icons/korp-v2/inbox.png", import.meta.url).href,
  "forms": new URL("../assets/icons/korp-v2/forms.png", import.meta.url).href,
  "compliance-bin": new URL("../assets/icons/korp-v2/compliance-bin.png", import.meta.url).href,
  "document": new URL("../assets/icons/korp-v2/document.png", import.meta.url).href,
  "memo": new URL("../assets/icons/korp-v2/memo.png", import.meta.url).href,
})


export const KORP_ICON_CATALOG = Object.freeze([
  Object.freeze({
    id: "click-audit",
    title: "ClickAudit",
    group: "modules",
    category: "AUDIT / CONFIRMATION",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["click-audit"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/click-audit.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/click-audit.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/click-audit.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "fidget",
    title: "Fidget",
    group: "modules",
    category: "STABILIZATION",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["fidget"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/fidget.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/fidget.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/fidget.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "bloom",
    title: "Bloom",
    group: "modules",
    category: "CARE / CLEANING",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["bloom"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/bloom.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/bloom.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/bloom.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "corner-watch",
    title: "Corner Watch",
    group: "modules",
    category: "IDLE / SCREENSAVER",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["corner-watch"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/corner-watch.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/corner-watch.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/corner-watch.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "bubble-wrap",
    title: "Bublinková Fólie",
    group: "modules",
    category: "STABILIZATION",
    accent: "pink",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["bubble-wrap"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/bubble-wrap.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/bubble-wrap.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/bubble-wrap.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "button-compliance",
    title: "Button Compliance",
    group: "modules",
    category: "AUDIT / CONFIRMATION",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["button-compliance"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/button-compliance.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/button-compliance.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/button-compliance.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "surface-compliance",
    title: "Surface Compliance",
    group: "modules",
    category: "CARE / CLEANING",
    accent: "orange",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["surface-compliance"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/surface-compliance.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/surface-compliance.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/surface-compliance.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "shape-compliance",
    title: "Shape Compliance",
    group: "modules",
    category: "ALIGNMENT",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["shape-compliance"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/shape-compliance.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/shape-compliance.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/shape-compliance.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "attention-runner",
    title: "Attention Runner",
    group: "modules",
    category: "ATTENTION SPLIT",
    accent: "orange",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["attention-runner"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/attention-runner.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/attention-runner.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/attention-runner.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "zen-garden",
    title: "Zenová Zahrádka",
    group: "modules",
    category: "DESK OBJECT / CARE",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["zen-garden"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/zen-garden.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/zen-garden.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/zen-garden.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "newton-cradle",
    title: "Newtonova Kolíbka",
    group: "modules",
    category: "DESK OBJECT / IDLE",
    accent: "brass",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["newton-cradle"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/newton-cradle.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/newton-cradle.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/newton-cradle.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "work-blob",
    title: "Privacy Work Blob",
    group: "modules",
    category: "OVERLAY / PRIVACY",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["work-blob"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/modules/work-blob.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/modules/work-blob.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/modules/work-blob.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "audit-generic",
    title: "Audit — obecný",
    group: "system",
    category: "DOCUMENT",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["folder-entry"]),
    intendedSize: 30,
    runtimeUrl: runtimeUrls["audit-generic"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/audit-generic.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/audit-generic.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/audit-generic.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "audit-packet",
    title: "Auditní dávka",
    group: "system",
    category: "CORE LOOP",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["folder-entry"]),
    intendedSize: 30,
    runtimeUrl: runtimeUrls["audit-packet"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/audit-packet.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/audit-packet.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/audit-packet.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "evidence",
    title: "Evidence / EV",
    group: "system",
    category: "CORE LOOP",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["folder-entry"]),
    intendedSize: 30,
    runtimeUrl: runtimeUrls["evidence"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/evidence.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/evidence.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/evidence.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "inbox",
    title: "Doručené",
    group: "system",
    category: "FOLDER",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["inbox"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/inbox.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/inbox.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/inbox.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "forms",
    title: "Formuláře",
    group: "system",
    category: "FOLDER",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["forms"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/forms.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/forms.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/forms.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "wellbeing",
    title: "Wellbeing",
    group: "system",
    category: "FOLDER",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["wellbeing"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/wellbeing.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/wellbeing.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/wellbeing.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "care-alignment",
    title: "Care & Alignment",
    group: "system",
    category: "FOLDER",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["care-alignment"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/care-alignment.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/care-alignment.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/care-alignment.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "pending-confirmations",
    title: "Čekající potvrzení",
    group: "system",
    category: "FOLDER",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["pending-confirmations"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/pending-confirmations.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/pending-confirmations.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/pending-confirmations.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "certifications",
    title: "Certifikace",
    group: "system",
    category: "DOCUMENT / FOLDER",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["certifications"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/certifications.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/certifications.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/certifications.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "knowledge-base",
    title: "Knowledge Base",
    group: "system",
    category: "SYSTEM",
    accent: "blue",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["knowledge-base"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/knowledge-base.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/knowledge-base.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/knowledge-base.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "archive",
    title: "Archiv",
    group: "system",
    category: "SYSTEM FOLDER",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["archive"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/archive.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/archive.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/archive.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "compliance-bin",
    title: "Compliance Bin",
    group: "system",
    category: "SYSTEM",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["desktop"]),
    intendedSize: 40,
    runtimeUrl: runtimeUrls["compliance-bin"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/compliance-bin.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/compliance-bin.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/compliance-bin.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "folder-closed",
    title: "Složka — zavřená",
    group: "system",
    category: "GENERIC",
    accent: "brass",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["folder-closed"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/folder-closed.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/folder-closed.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/folder-closed.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "folder-open",
    title: "Složka — otevřená",
    group: "system",
    category: "GENERIC",
    accent: "brass",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["folder-open"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/folder-open.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/folder-open.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/folder-open.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "document",
    title: "Dokument",
    group: "system",
    category: "GENERIC",
    accent: "blue",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["folder-entry"]),
    intendedSize: 30,
    runtimeUrl: runtimeUrls["document"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/document.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/document.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/document.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "memo",
    title: "Interní memo",
    group: "system",
    category: "DOCUMENT",
    accent: "red",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze(["folder-entry"]),
    intendedSize: 30,
    runtimeUrl: runtimeUrls["memo"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/memo.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/memo.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/memo.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "settings",
    title: "Nastavení",
    group: "system",
    category: "SYSTEM",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["settings"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/settings.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/settings.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/settings.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "computer",
    title: "Tento počítač",
    group: "system",
    category: "SYSTEM",
    accent: "green",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["computer"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/computer.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/computer.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/computer.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "locked-pending",
    title: "Locked / Pending",
    group: "system",
    category: "STATE",
    accent: "yellow",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["locked-pending"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/locked-pending.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/locked-pending.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/locked-pending.ico",
      variants: Object.freeze({
      }),
    }),
  }),
  Object.freeze({
    id: "audit-cycle",
    title: "Audit Cycle",
    group: "system",
    category: "PRESTIGE / ARCHIVE",
    accent: "blue",
    intrinsicWidth: 64,
    intrinsicHeight: 64,
    intendedSlots: Object.freeze([]),
    intendedSize: null,
    runtimeUrl: runtimeUrls["audit-cycle"] ?? null,
    variants: Object.freeze({
    }),
    sourceReferences: Object.freeze({
      png64: "design/icon-source/k0rp-icons-v2/png/64/system/audit-cycle.png",
      png256: "design/icon-source/k0rp-icons-v2/png/256/system/audit-cycle.png",
      ico: "design/icon-source/k0rp-icons-v2/ico/system/audit-cycle.ico",
      variants: Object.freeze({
      }),
    }),
  }),
])

export const KORP_RUNTIME_ICON_IDS = Object.freeze(
  KORP_ICON_CATALOG.filter(({ runtimeUrl }) => Boolean(runtimeUrl)).map(({ id }) => id),
)

const iconById = new Map(KORP_ICON_CATALOG.map((icon) => [icon.id, icon]))

export function getKorpIcon(id) {
  return typeof id === 'string' ? iconById.get(id) ?? null : null
}

export function resolveKorpRuntimeIcon(id) {
  const icon = getKorpIcon(id)
  return icon?.runtimeUrl ? icon : null
}
